# Generated by Django 3.1.4 on 2022-01-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_no', models.TextField(unique=True)),
                ('car_name', models.TextField()),
                ('time_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
